// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/jwt.proto

package jwt

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_proto_jwt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jwt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_jwt_proto_rawDescGZIP(), []int{0}
}

func (x *TokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	TokenType     string                 `protobuf:"bytes,3,opt,name=tokenType,proto3" json:"tokenType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_proto_jwt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jwt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_proto_jwt_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GenerateRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GenerateRequest) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_proto_jwt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jwt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_jwt_proto_rawDescGZIP(), []int{2}
}

func (x *TokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Claims        *Claims `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_proto_jwt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jwt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_proto_jwt_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ValidateResponse) GetClaims() *Claims {
	if x != nil {
		return x.Claims
	}
	return nil
}

type Claims struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Claims) Reset() {
	*x = Claims{}
	mi := &file_proto_jwt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claims) ProtoMessage() {}

func (x *Claims) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jwt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claims.ProtoReflect.Descriptor instead.
func (*Claims) Descriptor() ([]byte, []int) {
	return file_proto_jwt_proto_rawDescGZIP(), []int{4}
}

func (x *Claims) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Claims) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

var File_proto_jwt_proto protoreflect.FileDescriptor

const file_proto_jwt_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/jwt.proto\x12\x03jwt\x1a\x1cgoogle/api/annotations.proto\"$\n" +
	"\fTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"W\n" +
	"\x0fGenerateRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x1c\n" +
	"\ttokenType\x18\x03 \x01(\tR\ttokenType\"%\n" +
	"\rTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"Q\n" +
	"\x10ValidateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\x06claims\x18\x02 \x01(\v2\v.jwt.ClaimsR\x06claims\"0\n" +
	"\x06Claims\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login2\xd7\x01\n" +
	"\n" +
	"JwtService\x12S\n" +
	"\fRefreshToken\x12\x11.jwt.TokenRequest\x1a\x12.jwt.TokenResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/jwt/refreshToken\x129\n" +
	"\rValidateToken\x12\x11.jwt.TokenRequest\x1a\x15.jwt.ValidateResponse\x129\n" +
	"\rGenerateToken\x12\x14.jwt.GenerateRequest\x1a\x12.jwt.TokenResponseB\x12Z\x10internal/api/jwtb\x06proto3"

var (
	file_proto_jwt_proto_rawDescOnce sync.Once
	file_proto_jwt_proto_rawDescData []byte
)

func file_proto_jwt_proto_rawDescGZIP() []byte {
	file_proto_jwt_proto_rawDescOnce.Do(func() {
		file_proto_jwt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_jwt_proto_rawDesc), len(file_proto_jwt_proto_rawDesc)))
	})
	return file_proto_jwt_proto_rawDescData
}

var file_proto_jwt_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_jwt_proto_goTypes = []any{
	(*TokenRequest)(nil),     // 0: jwt.TokenRequest
	(*GenerateRequest)(nil),  // 1: jwt.GenerateRequest
	(*TokenResponse)(nil),    // 2: jwt.TokenResponse
	(*ValidateResponse)(nil), // 3: jwt.ValidateResponse
	(*Claims)(nil),           // 4: jwt.Claims
}
var file_proto_jwt_proto_depIdxs = []int32{
	4, // 0: jwt.ValidateResponse.claims:type_name -> jwt.Claims
	0, // 1: jwt.JwtService.RefreshToken:input_type -> jwt.TokenRequest
	0, // 2: jwt.JwtService.ValidateToken:input_type -> jwt.TokenRequest
	1, // 3: jwt.JwtService.GenerateToken:input_type -> jwt.GenerateRequest
	2, // 4: jwt.JwtService.RefreshToken:output_type -> jwt.TokenResponse
	3, // 5: jwt.JwtService.ValidateToken:output_type -> jwt.ValidateResponse
	2, // 6: jwt.JwtService.GenerateToken:output_type -> jwt.TokenResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_jwt_proto_init() }
func file_proto_jwt_proto_init() {
	if File_proto_jwt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_jwt_proto_rawDesc), len(file_proto_jwt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_jwt_proto_goTypes,
		DependencyIndexes: file_proto_jwt_proto_depIdxs,
		MessageInfos:      file_proto_jwt_proto_msgTypes,
	}.Build()
	File_proto_jwt_proto = out.File
	file_proto_jwt_proto_goTypes = nil
	file_proto_jwt_proto_depIdxs = nil
}
